WSL support in refactor
shivapoudel/github-material-icons-extension pull request #3
Opened 2021-07-13 08:25 UTC by 4086606

Apply fixes to get `build` task working in WSL2 Ubuntu 20.04.

2021-07-13 22:44 UTC, shivapoudel requested changes
Please have a look to some review comments!

2021-07-13 22:44 UTC, shivapoudel commented on package.json
> +    "@parcel/config-default": "2.0.0-beta.2",
@4086606 Can this be on `devDependencies`?

2021-07-13 22:44 UTC, shivapoudel commented on scripts/build-src.js
> +    mode: 'development',
@4086606 Production expected!

2021-07-13 22:44 UTC, shivapoudel commented on scripts/build-src.js
> +
If this blank line can be minimized!

2021-07-13 22:44 UTC, shivapoudel commented on package.json
> +    "node": ">=12.0.0"
Any reason a higher version of the node is required? There is already `>=`

2021-07-13 22:44 UTC, shivapoudel commented on package.json
> +    "deasync": "0.1.16"
@4086606 I am not sure Deasync has any reasons to be included for WSL support. This can be raised in the next PR to keep this PR clean.

2021-07-13 22:44 UTC, shivapoudel commented on .parcelrc
> +}
@4086606 EOL is missing!

2021-07-13 22:45 UTC, shivapoudel commented on scripts/build-src.js
> +    mode: 'development',
Also, ensure source map is not generated for extension filesize and also the script is minified.

2021-07-13 22:46 UTC, 4086606 commented on package.json
> +    "deasync": "0.1.16"
It's a override when upgrading to Parcel V2 that allows deasync to resolve correctly

2021-07-13 22:47 UTC, 4086606 commented on package.json
> +    "@parcel/config-default": "2.0.0-beta.2",
Sure

2021-07-13 22:47 UTC, 4086606 commented on scripts/build-src.js
> +    mode: 'development',
Was developing, will fix if you can't

2021-07-13 22:49 UTC, 4086606 commented on package.json
> +    "node": ">=12.0.0"
Upping the value shows the developer which version of Node they need, helps keep maintainability and portability up

2021-07-13 22:55 UTC, 4086606 commented on scripts/build-src.js
> +
```suggestion
```

2021-07-13 22:59 UTC, shivapoudel commented on package.json
> +    "deasync": "0.1.16"
Nice catch, thanks 👍

2021-07-13 23:07 UTC, shivapoudel commented on scripts/build-src.js
> +    mode: 'development',
It will be better if you can resolve this so that I will overall test changes after the merge in the original PR.

2021-07-14 02:58 UTC, closed without merging

2021-07-14 02:59 UTC, shivapoudel commented
@4086606 Since the original PR is merged. Can you raise a PR over there!